// Shared country code list for phone-number pickers across the app.
// Used by:
//   - client/src/components/StudentFormDialog.js          (LUC student phone)
//   - client/src/components/skillhub/SkillhubStudentFormDialog.js
//     (Skillhub student / mother / father phones)
//
// Order: top section is the app's primary region (Gulf + South Asia) kept in
// the order it had historically. The rest is alphabetical by country name.
// Shared ITU codes (e.g. +1 covers many Caribbean countries, +7 covers Russia
// & Kazakhstan) appear as multiple entries — `findCountryCode` returns the
// first match in array order, so the country with the more general code stays
// the canonical read-back. That's intentional; the picker just needs every
// country to be *searchable* by name.
//
// Phone format stored in the model is "<+code> <number>" (single space).
// `findCountryCode` is the source of truth for stripping that prefix back.

export const COUNTRY_CODES = [
    // ─── Priority (Gulf + South Asia, in original app order) ────────────────
    { code: '+971', country: 'UAE',          label: '+971 (UAE)' },
    { code: '+966', country: 'Saudi Arabia', label: '+966 (Saudi Arabia)' },
    { code: '+974', country: 'Qatar',        label: '+974 (Qatar)' },
    { code: '+965', country: 'Kuwait',       label: '+965 (Kuwait)' },
    { code: '+973', country: 'Bahrain',      label: '+973 (Bahrain)' },
    { code: '+968', country: 'Oman',         label: '+968 (Oman)' },
    { code: '+91',  country: 'India',        label: '+91 (India)' },
    { code: '+92',  country: 'Pakistan',     label: '+92 (Pakistan)' },

    // ─── All other countries (alphabetical) ─────────────────────────────────
    { code: '+93',   country: 'Afghanistan',           label: '+93 (Afghanistan)' },
    { code: '+355',  country: 'Albania',               label: '+355 (Albania)' },
    { code: '+213',  country: 'Algeria',               label: '+213 (Algeria)' },
    { code: '+376',  country: 'Andorra',               label: '+376 (Andorra)' },
    { code: '+244',  country: 'Angola',                label: '+244 (Angola)' },
    { code: '+1',    country: 'Antigua and Barbuda',   label: '+1 (Antigua and Barbuda)' },
    { code: '+54',   country: 'Argentina',             label: '+54 (Argentina)' },
    { code: '+374',  country: 'Armenia',               label: '+374 (Armenia)' },
    { code: '+297',  country: 'Aruba',                 label: '+297 (Aruba)' },
    { code: '+61',   country: 'Australia',             label: '+61 (Australia)' },
    { code: '+43',   country: 'Austria',               label: '+43 (Austria)' },
    { code: '+994',  country: 'Azerbaijan',            label: '+994 (Azerbaijan)' },
    { code: '+1',    country: 'Bahamas',               label: '+1 (Bahamas)' },
    { code: '+880',  country: 'Bangladesh',            label: '+880 (Bangladesh)' },
    { code: '+1',    country: 'Barbados',              label: '+1 (Barbados)' },
    { code: '+375',  country: 'Belarus',               label: '+375 (Belarus)' },
    { code: '+32',   country: 'Belgium',               label: '+32 (Belgium)' },
    { code: '+501',  country: 'Belize',                label: '+501 (Belize)' },
    { code: '+229',  country: 'Benin',                 label: '+229 (Benin)' },
    { code: '+975',  country: 'Bhutan',                label: '+975 (Bhutan)' },
    { code: '+591',  country: 'Bolivia',               label: '+591 (Bolivia)' },
    { code: '+387',  country: 'Bosnia and Herzegovina', label: '+387 (Bosnia and Herzegovina)' },
    { code: '+267',  country: 'Botswana',              label: '+267 (Botswana)' },
    { code: '+55',   country: 'Brazil',                label: '+55 (Brazil)' },
    { code: '+673',  country: 'Brunei',                label: '+673 (Brunei)' },
    { code: '+359',  country: 'Bulgaria',              label: '+359 (Bulgaria)' },
    { code: '+226',  country: 'Burkina Faso',          label: '+226 (Burkina Faso)' },
    { code: '+257',  country: 'Burundi',               label: '+257 (Burundi)' },
    { code: '+855',  country: 'Cambodia',              label: '+855 (Cambodia)' },
    { code: '+237',  country: 'Cameroon',              label: '+237 (Cameroon)' },
    { code: '+1',    country: 'Canada',                label: '+1 (Canada)' },
    { code: '+238',  country: 'Cape Verde',            label: '+238 (Cape Verde)' },
    { code: '+236',  country: 'Central African Republic', label: '+236 (Central African Republic)' },
    { code: '+235',  country: 'Chad',                  label: '+235 (Chad)' },
    { code: '+56',   country: 'Chile',                 label: '+56 (Chile)' },
    { code: '+86',   country: 'China',                 label: '+86 (China)' },
    { code: '+57',   country: 'Colombia',              label: '+57 (Colombia)' },
    { code: '+269',  country: 'Comoros',               label: '+269 (Comoros)' },
    { code: '+242',  country: 'Congo (Brazzaville)',   label: '+242 (Congo - Brazzaville)' },
    { code: '+243',  country: 'Congo (Kinshasa, DRC)', label: '+243 (Congo - Kinshasa, DRC)' },
    { code: '+682',  country: 'Cook Islands',          label: '+682 (Cook Islands)' },
    { code: '+506',  country: 'Costa Rica',            label: '+506 (Costa Rica)' },
    { code: '+385',  country: 'Croatia',               label: '+385 (Croatia)' },
    { code: '+53',   country: 'Cuba',                  label: '+53 (Cuba)' },
    { code: '+357',  country: 'Cyprus',                label: '+357 (Cyprus)' },
    { code: '+420',  country: 'Czech Republic',        label: '+420 (Czech Republic)' },
    { code: '+45',   country: 'Denmark',               label: '+45 (Denmark)' },
    { code: '+253',  country: 'Djibouti',              label: '+253 (Djibouti)' },
    { code: '+1',    country: 'Dominica',              label: '+1 (Dominica)' },
    { code: '+1',    country: 'Dominican Republic',    label: '+1 (Dominican Republic)' },
    { code: '+670',  country: 'East Timor',            label: '+670 (East Timor)' },
    { code: '+593',  country: 'Ecuador',               label: '+593 (Ecuador)' },
    { code: '+20',   country: 'Egypt',                 label: '+20 (Egypt)' },
    { code: '+503',  country: 'El Salvador',           label: '+503 (El Salvador)' },
    { code: '+240',  country: 'Equatorial Guinea',     label: '+240 (Equatorial Guinea)' },
    { code: '+291',  country: 'Eritrea',               label: '+291 (Eritrea)' },
    { code: '+372',  country: 'Estonia',               label: '+372 (Estonia)' },
    { code: '+268',  country: 'Eswatini',              label: '+268 (Eswatini)' },
    { code: '+251',  country: 'Ethiopia',              label: '+251 (Ethiopia)' },
    { code: '+298',  country: 'Faroe Islands',         label: '+298 (Faroe Islands)' },
    { code: '+679',  country: 'Fiji',                  label: '+679 (Fiji)' },
    { code: '+358',  country: 'Finland',               label: '+358 (Finland)' },
    { code: '+33',   country: 'France',                label: '+33 (France)' },
    { code: '+689',  country: 'French Polynesia',      label: '+689 (French Polynesia)' },
    { code: '+241',  country: 'Gabon',                 label: '+241 (Gabon)' },
    { code: '+220',  country: 'Gambia',                label: '+220 (Gambia)' },
    { code: '+995',  country: 'Georgia',               label: '+995 (Georgia)' },
    { code: '+49',   country: 'Germany',               label: '+49 (Germany)' },
    { code: '+233',  country: 'Ghana',                 label: '+233 (Ghana)' },
    { code: '+350',  country: 'Gibraltar',             label: '+350 (Gibraltar)' },
    { code: '+30',   country: 'Greece',                label: '+30 (Greece)' },
    { code: '+299',  country: 'Greenland',             label: '+299 (Greenland)' },
    { code: '+1',    country: 'Grenada',               label: '+1 (Grenada)' },
    { code: '+1',    country: 'Guam',                  label: '+1 (Guam)' },
    { code: '+502',  country: 'Guatemala',             label: '+502 (Guatemala)' },
    { code: '+224',  country: 'Guinea',                label: '+224 (Guinea)' },
    { code: '+245',  country: 'Guinea-Bissau',         label: '+245 (Guinea-Bissau)' },
    { code: '+592',  country: 'Guyana',                label: '+592 (Guyana)' },
    { code: '+509',  country: 'Haiti',                 label: '+509 (Haiti)' },
    { code: '+504',  country: 'Honduras',              label: '+504 (Honduras)' },
    { code: '+852',  country: 'Hong Kong',             label: '+852 (Hong Kong)' },
    { code: '+36',   country: 'Hungary',               label: '+36 (Hungary)' },
    { code: '+354',  country: 'Iceland',               label: '+354 (Iceland)' },
    { code: '+62',   country: 'Indonesia',             label: '+62 (Indonesia)' },
    { code: '+98',   country: 'Iran',                  label: '+98 (Iran)' },
    { code: '+964',  country: 'Iraq',                  label: '+964 (Iraq)' },
    { code: '+353',  country: 'Ireland',               label: '+353 (Ireland)' },
    { code: '+972',  country: 'Israel',                label: '+972 (Israel)' },
    { code: '+39',   country: 'Italy',                 label: '+39 (Italy)' },
    { code: '+225',  country: 'Ivory Coast',           label: '+225 (Ivory Coast)' },
    { code: '+1',    country: 'Jamaica',               label: '+1 (Jamaica)' },
    { code: '+81',   country: 'Japan',                 label: '+81 (Japan)' },
    { code: '+962',  country: 'Jordan',                label: '+962 (Jordan)' },
    { code: '+7',    country: 'Kazakhstan',            label: '+7 (Kazakhstan)' },
    { code: '+254',  country: 'Kenya',                 label: '+254 (Kenya)' },
    { code: '+686',  country: 'Kiribati',              label: '+686 (Kiribati)' },
    { code: '+383',  country: 'Kosovo',                label: '+383 (Kosovo)' },
    { code: '+996',  country: 'Kyrgyzstan',            label: '+996 (Kyrgyzstan)' },
    { code: '+856',  country: 'Laos',                  label: '+856 (Laos)' },
    { code: '+371',  country: 'Latvia',                label: '+371 (Latvia)' },
    { code: '+961',  country: 'Lebanon',               label: '+961 (Lebanon)' },
    { code: '+266',  country: 'Lesotho',               label: '+266 (Lesotho)' },
    { code: '+231',  country: 'Liberia',               label: '+231 (Liberia)' },
    { code: '+218',  country: 'Libya',                 label: '+218 (Libya)' },
    { code: '+423',  country: 'Liechtenstein',         label: '+423 (Liechtenstein)' },
    { code: '+370',  country: 'Lithuania',             label: '+370 (Lithuania)' },
    { code: '+352',  country: 'Luxembourg',            label: '+352 (Luxembourg)' },
    { code: '+853',  country: 'Macau',                 label: '+853 (Macau)' },
    { code: '+261',  country: 'Madagascar',            label: '+261 (Madagascar)' },
    { code: '+265',  country: 'Malawi',                label: '+265 (Malawi)' },
    { code: '+60',   country: 'Malaysia',              label: '+60 (Malaysia)' },
    { code: '+960',  country: 'Maldives',              label: '+960 (Maldives)' },
    { code: '+223',  country: 'Mali',                  label: '+223 (Mali)' },
    { code: '+356',  country: 'Malta',                 label: '+356 (Malta)' },
    { code: '+692',  country: 'Marshall Islands',      label: '+692 (Marshall Islands)' },
    { code: '+222',  country: 'Mauritania',            label: '+222 (Mauritania)' },
    { code: '+230',  country: 'Mauritius',             label: '+230 (Mauritius)' },
    { code: '+52',   country: 'Mexico',                label: '+52 (Mexico)' },
    { code: '+691',  country: 'Micronesia',            label: '+691 (Micronesia)' },
    { code: '+373',  country: 'Moldova',               label: '+373 (Moldova)' },
    { code: '+377',  country: 'Monaco',                label: '+377 (Monaco)' },
    { code: '+976',  country: 'Mongolia',              label: '+976 (Mongolia)' },
    { code: '+382',  country: 'Montenegro',            label: '+382 (Montenegro)' },
    { code: '+212',  country: 'Morocco',               label: '+212 (Morocco)' },
    { code: '+258',  country: 'Mozambique',            label: '+258 (Mozambique)' },
    { code: '+95',   country: 'Myanmar',               label: '+95 (Myanmar)' },
    { code: '+264',  country: 'Namibia',               label: '+264 (Namibia)' },
    { code: '+674',  country: 'Nauru',                 label: '+674 (Nauru)' },
    { code: '+977',  country: 'Nepal',                 label: '+977 (Nepal)' },
    { code: '+31',   country: 'Netherlands',           label: '+31 (Netherlands)' },
    { code: '+687',  country: 'New Caledonia',         label: '+687 (New Caledonia)' },
    { code: '+64',   country: 'New Zealand',           label: '+64 (New Zealand)' },
    { code: '+505',  country: 'Nicaragua',             label: '+505 (Nicaragua)' },
    { code: '+227',  country: 'Niger',                 label: '+227 (Niger)' },
    { code: '+234',  country: 'Nigeria',               label: '+234 (Nigeria)' },
    { code: '+850',  country: 'North Korea',           label: '+850 (North Korea)' },
    { code: '+389',  country: 'North Macedonia',       label: '+389 (North Macedonia)' },
    { code: '+47',   country: 'Norway',                label: '+47 (Norway)' },
    { code: '+680',  country: 'Palau',                 label: '+680 (Palau)' },
    { code: '+970',  country: 'Palestine',             label: '+970 (Palestine)' },
    { code: '+507',  country: 'Panama',                label: '+507 (Panama)' },
    { code: '+675',  country: 'Papua New Guinea',      label: '+675 (Papua New Guinea)' },
    { code: '+595',  country: 'Paraguay',              label: '+595 (Paraguay)' },
    { code: '+51',   country: 'Peru',                  label: '+51 (Peru)' },
    { code: '+63',   country: 'Philippines',           label: '+63 (Philippines)' },
    { code: '+48',   country: 'Poland',                label: '+48 (Poland)' },
    { code: '+351',  country: 'Portugal',              label: '+351 (Portugal)' },
    { code: '+1',    country: 'Puerto Rico',           label: '+1 (Puerto Rico)' },
    { code: '+262',  country: 'Réunion',               label: '+262 (Réunion)' },
    { code: '+40',   country: 'Romania',               label: '+40 (Romania)' },
    { code: '+7',    country: 'Russia',                label: '+7 (Russia)' },
    { code: '+250',  country: 'Rwanda',                label: '+250 (Rwanda)' },
    { code: '+1',    country: 'Saint Kitts and Nevis', label: '+1 (Saint Kitts and Nevis)' },
    { code: '+1',    country: 'Saint Lucia',           label: '+1 (Saint Lucia)' },
    { code: '+1',    country: 'Saint Vincent',         label: '+1 (Saint Vincent and the Grenadines)' },
    { code: '+685',  country: 'Samoa',                 label: '+685 (Samoa)' },
    { code: '+378',  country: 'San Marino',            label: '+378 (San Marino)' },
    { code: '+239',  country: 'Sao Tome and Principe', label: '+239 (Sao Tome and Principe)' },
    { code: '+221',  country: 'Senegal',               label: '+221 (Senegal)' },
    { code: '+381',  country: 'Serbia',                label: '+381 (Serbia)' },
    { code: '+248',  country: 'Seychelles',            label: '+248 (Seychelles)' },
    { code: '+232',  country: 'Sierra Leone',          label: '+232 (Sierra Leone)' },
    { code: '+65',   country: 'Singapore',             label: '+65 (Singapore)' },
    { code: '+421',  country: 'Slovakia',              label: '+421 (Slovakia)' },
    { code: '+386',  country: 'Slovenia',              label: '+386 (Slovenia)' },
    { code: '+677',  country: 'Solomon Islands',       label: '+677 (Solomon Islands)' },
    { code: '+252',  country: 'Somalia',               label: '+252 (Somalia)' },
    { code: '+27',   country: 'South Africa',          label: '+27 (South Africa)' },
    { code: '+82',   country: 'South Korea',           label: '+82 (South Korea)' },
    { code: '+211',  country: 'South Sudan',           label: '+211 (South Sudan)' },
    { code: '+34',   country: 'Spain',                 label: '+34 (Spain)' },
    { code: '+94',   country: 'Sri Lanka',             label: '+94 (Sri Lanka)' },
    { code: '+249',  country: 'Sudan',                 label: '+249 (Sudan)' },
    { code: '+597',  country: 'Suriname',              label: '+597 (Suriname)' },
    { code: '+46',   country: 'Sweden',                label: '+46 (Sweden)' },
    { code: '+41',   country: 'Switzerland',           label: '+41 (Switzerland)' },
    { code: '+963',  country: 'Syria',                 label: '+963 (Syria)' },
    { code: '+886',  country: 'Taiwan',                label: '+886 (Taiwan)' },
    { code: '+992',  country: 'Tajikistan',            label: '+992 (Tajikistan)' },
    { code: '+255',  country: 'Tanzania',              label: '+255 (Tanzania)' },
    { code: '+66',   country: 'Thailand',              label: '+66 (Thailand)' },
    { code: '+228',  country: 'Togo',                  label: '+228 (Togo)' },
    { code: '+676',  country: 'Tonga',                 label: '+676 (Tonga)' },
    { code: '+1',    country: 'Trinidad and Tobago',   label: '+1 (Trinidad and Tobago)' },
    { code: '+216',  country: 'Tunisia',               label: '+216 (Tunisia)' },
    { code: '+90',   country: 'Turkey',                label: '+90 (Turkey)' },
    { code: '+993',  country: 'Turkmenistan',          label: '+993 (Turkmenistan)' },
    { code: '+688',  country: 'Tuvalu',                label: '+688 (Tuvalu)' },
    { code: '+256',  country: 'Uganda',                label: '+256 (Uganda)' },
    { code: '+380',  country: 'Ukraine',               label: '+380 (Ukraine)' },
    { code: '+44',   country: 'United Kingdom',        label: '+44 (United Kingdom)' },
    { code: '+1',    country: 'United States',         label: '+1 (United States / Canada)' },
    { code: '+598',  country: 'Uruguay',               label: '+598 (Uruguay)' },
    { code: '+998',  country: 'Uzbekistan',            label: '+998 (Uzbekistan)' },
    { code: '+678',  country: 'Vanuatu',               label: '+678 (Vanuatu)' },
    { code: '+379',  country: 'Vatican City',          label: '+379 (Vatican City)' },
    { code: '+58',   country: 'Venezuela',             label: '+58 (Venezuela)' },
    { code: '+84',   country: 'Vietnam',               label: '+84 (Vietnam)' },
    { code: '+967',  country: 'Yemen',                 label: '+967 (Yemen)' },
    { code: '+260',  country: 'Zambia',                label: '+260 (Zambia)' },
    { code: '+263',  country: 'Zimbabwe',              label: '+263 (Zimbabwe)' },
];

// Default code used when a stored phone has no recognizable prefix yet.
export const DEFAULT_COUNTRY_CODE = '+971';

// Returns the COUNTRY_CODES entry whose `code` is a prefix of `phone`.
// Falls back to the first entry (UAE) when nothing matches — matches the
// existing behavior of `COUNTRY_CODES[0]` used as the picker default.
export const findCountryCode = (phone) => {
    if (!phone) return COUNTRY_CODES[0];
    return COUNTRY_CODES.find((c) => phone.startsWith(c.code)) || COUNTRY_CODES[0];
};
